### ISSUE TITLE
Proposal for first public foundation team npm module  

### ISSUE THREAD

**Issue by fraserxu** [envato/market-api-gateway-js#1]
### Context

This is the first **public** foundation team npm module. 
- **module name**: @envato-marketplace-foundation/market-api-gateway-js
- **module owner**: [@envato-marketplace-foundation](https://www.npmjs.com/~envato-marketplace-foundation)
### Goal of this module

This module is a thin wrapper of [https://build.envato.com/api](https://build.envato.com/api), which aims to provide an easy to use api inside JavaScript project. It will be first used in `market-hub` project as test, and then used in `market-shopfront` project(the main user of this module).

Please check more details and usage information in [the homepage](https://github.com/envato/marketplace-api-gateway-js).

Currently this module runs **natively** on nodejs@v4 without any compiler. In the near future if we want it to run inside browser, we may introduce `browserify` or `webpack` to compile the source code to ES5 for browser that does not support the new feature in ES6. However this will be next step as it's mostly an internal module which may only used in the customer group. 

Even though more of an internal module rather than for public use, this module should be a good way to demonstrate
- the **npm workflow** inside JavaScript based project
  - how to write npm modules
  - how to install scoped npm modules
  - how to publish npm modules
- how to **share code** between projects, teams, companies
- how to improve and **force code quality** through open source code
- how to **separate concern** out of potentail monolith code
- how to manage and **maintain open source JavaScript project**
- prepare for **more shareable stuff**(code, design, documentation)
- prepare for **private** npm stuff 
### Pre-publish check list

Check list before publishing to npm
- [x] make Github repo public
- [x] register `envato-marketplace-foundation` user with `market-foundation-dev@envato.com`
- [x] share the npm user password to 1 password for team
- [x] add devs to collaborator so we can publish with our own npm account
- [x] publish to npm public registry
- [x] use module in `market-hub`
- [x] use module in `market-shopfront`
#### FAQ

**Why not private npm module?**
- Private npm module is not free and charged by per user, could cost lots of money 
- Lack of experience on manage private npm modules
- Need a way to manage tokens for local dev, CI setup, deployment process

**Why not use Github instead of NPM?**
- Standard and recommended way to manage NPM modules
- _todo_

**Comment by pawelgalazka** [comment]
Looks like a very good idea 👍 I would only propose maybe more "standardised" name like "marketplace-js-sdk"

**Comment by fraserxu** [comment]
@pawelgalazka :thinking_face: we may have lots of external services exposed from marketplace, api-gateway and sso-js for example, `marketplace-js` is a little general in this case no?

Or something like "marketplace-api-gateway-js-sdk"?

**Comment by pawelgalazka** [comment]
Hmm... is `sso-js` only marketplace oriented ? Overall I don't have any strong preferences here, it was just a though.

**Comment by fraserxu** [comment]
`sso-js` is not marketplace oriented, it's Envato wide and used in all other projects within Envato, site, studio, elements.

**Comment by fraserxu** [comment]
Done. Closing...
